### PR TITLE
finished the screen for student list

### PR DESCRIPTION
**Pull request by potetz**
no sorting yet (just the view)
tried linking the log out button to the login screen but not sure if I shouldn't have done that
header is coded directly into the html of the student list for now

### CODE REVIEW

**Comment by potetz** [comment]
[Create Student List table](https://trello.com/c/no1c6iAn/8-create-student-list-table)

**Review by daniddelrio — COMMENTED** [review]
Very solid work. Not gonna request for specific changes since your code looks fine, but a few general suggestions that maybe you can try out:

1. Check if the table looks better without the gray border in between each column? So that it'll look like the only borders will be in between each row.
2. Check also if a lighter shade for the border is better
3. Try making the "View" and "Update" really look like buttons (like the [Bootstrap buttons](https://getbootstrap.com/docs/4.0/components/buttons/) so that the user will know right away that they're two separate buttons.
4. Lastly, tinker around with [`em` and `rem` instead of `px`](https://medium.com/code-better/css-units-for-font-size-px-em-rem-79f7e592bb97) whenever you deal with sizes in CSS. Will help with responsiveness!

**Comment by potetz** [comment]
edited the table and the measurements now but unsure whether I used em and rem correctly

**Comment by daniddelrio** [comment]
Sorry, super last minor comments:
1. I take it back, I think it looks better pala with the column borders HAHA just make them not look too jarring/obvious by making the border color a little bit lighter
2. Add space between the View and Update buttons
3. Try making them have the same length so it looks nicer

**Comment by daniddelrio** [comment]
Approved!! I pushed a small change lang but otherwise goods na (it's for removing the left margin sa buttons hehe para magkatabi na lang yung dalawang buttons).

**Pull request merged**
